# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rsekaii
author: Rames Nagib AlJneibi
email: r.n.j@hotmail.com
description: >-
  Exploring my love for mathematics, and my personal growth

# Posts
show_excerpts: true

# URL
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rsekaii.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
github_username: rsekaii


# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding comments: false to that post's YAML Front Matter.
    shortname: rames

# Google Analytics
google_analytics: G-7S88B0TLVJ

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

# theme: minima
remote_theme: jekyll/minima
minima:
  skin: auto

plugins:
  - jekyll-feed
  - jekyll-remote-theme


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  sass_dir: _sass
  style: compressed
