title: Gishan's Notes
description: CSE undergraduate notes and learning resources.
baseurl: "" # Do not change for user/organization site
url: "https://gishanchamith.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

author:
  name: "Gishan Chamith"
  email: "gishan@gishanchamith.com.lk"

permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - CNAME

minima:
  skin: classic
