version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.2.5
    working_directory: ~/repo
    steps:
      - checkout
      - run: bundle install --jobs=3 --retry=3
  deploy:
    docker:
      - image: mesosphere/aws-cli
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - deploy:
          name: Deploy to AWS
          command: aws s3 sync /tmp/workspace/_site s3://david-merrick.com

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          filters:
            branches:
              only:
                - master