defaults: &defaults
  working_directory: ~/repo

version: 2.1
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install --jobs=3 --retry=3
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - persist_to_workspace:
          root: .
          paths:
            - _site/*
  deploy:
    <<: *defaults
    docker:
      - image: circleci/python:3.6.3
    environment:
      S3_BUCKET_NAME: david-merrick.com
    steps:
      - attach_workspace:
          at: ./
      - run: ls -la .
      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user
      - run:
          name: Upload to s3
          command: ~/.local/bin/aws s3 sync ./_site s3://$S3_BUCKET_NAME/ --delete --acl public-read

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master